phetsims/paper-land@main:
  - source: docs/use/paperLand-api.md
    dest: client/display/doc/paperLand-api.md
phetsims/paper-land@dev:
  - source: docs/use/paperLand-api.md
    dest: client/display/doc/paperLand-api.md