site_name: Paper Playground
repo_url: https://github.com/phetsims/paper-land

markdown_extensions:
    - toc:
        permalink: "#"

theme:
    name: readthedocs
    nav_style: dark
    prev_next_buttons_location: bottom

nav:
    - Home: README.md
    - Code Documentation: 
      - Board API: use/implementation-notes.md
      - Paper API: use/api.md
    - Paper Tutorial:
      - Camera Setup: tutorial/camera-setup.md
      - Legacy Tutorial: tutorial/tutorial.md
    - Contribution:
      # - How to Contribute: how to make this a redirect
      - Feature Wishlist: contribute/wishlist.md
      # - Community Code of Conduct: how to make this a redirect