site_name: Paper Playground
repo_url: https://github.com/phetsims/paper-land

markdown_extensions:
    - toc:
        permalink: "#"

theme:
    name: readthedocs
    nav_style: dark
    prev_next_buttons_location: bottom

nav:
    - Home: README.md
    - Tutorial:
      - Camera Setup: tutorial/camera-setup.md
      - Legacy Tutorial: tutorial/tutorial.md
    - Documentation: 
      - Board API: use/implementation-notes.md
      - Paper API: use/api.md
    - Contribution:
      - How to Contribute: CONTRIBUTING.md
      - Feature Wishlist: WISHLIST.md
      - Community Code of Conduct: CODE_OF_CONDUCT.md
    - About:
      - Contributors: about.md
      - Join Us: community.md
