# Project information
site_name: Paper Playground
site_url: https://phetsims.github.io/paper-land/
site_author: Brett Fiedler
site_description: >-
  Paper Playground is a tool for collaboratively designing multimodal web interactions 
  by mapping JavaScript code to real pieces of paper and manipulating them in your physical space!

# Repository
repo_name: paper-land
repo_url: https://github.com/phetsims/paper-land
edit_uri: edit/docs/docs

# Configuration
theme:
  name: material
  custom_dir: docs/overrides
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    # - navigation.prune
    - navigation.sections
    # - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  favicon: assets/paper-land-icon-3.svg
  logo: assets/paper-land-icon-3.svg
  name: material
  palette:
  - media: '(prefers-color-scheme: light)'
    primary: black
    accent: deep purple
    scheme: default
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
  - media: '(prefers-color-scheme: dark)'
    primary: black
    accent: deep purple
    scheme: slate
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono

# Plugins
plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
  - macros:
      render_by_default: false
      on_error_fail: false
      on_undefined: strict


# Customization
extra:
  annotate:
    json: [.s2]
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/phetsims/paper-land

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.pathconverter:
      base_path: 'community' # default: ''
      relative_path: '' # default ''
      absolute: false # default: false
      tags: 'a script img link object embed'
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
    - Home: index.md
    - Getting Started:
      - 1. Installation: setup/install.md
      - 2. Device Setup: setup/device-setup.md
      - 3. Overview: setup/interface-overview.md
      - 4. Creator Tutorial: setup/creator.md
    - Projects:
      - Multimodal Codesign: projects/codesign.md
      - Paper Craft: projects/craft.md
      - Microcontroller Integration: projects/microcontroller.md
      - Media Gallery: media-gallery.md
    - Resources: 
      - Walkthroughs: use/walkthroughs/walkthroughs.md
      - About Model-View-Controller: use/mvc.md
      - paperLand API: use/paperland-api.md
      - Downloadables: use/resources.md
      - Example Custom JS Papers: use/example-program.md
    - Community:
      - Join Us: community.md 
      - Contribute: CONTRIBUTING.md
      - Feature Wishlist: WISHLIST.md
      - Community Code of Conduct: CODE_OF_CONDUCT.md
      - AI Ethics: ai-ethics.md
