site_name: Paper Playground
repo_url: https://github.com/phetsims/paper-land

markdown_extensions:
    - toc:
        permalink: "#"

theme:
    name: readthedocs
    nav_style: dark
    prev_next_buttons_location: bottom

nav:
    - Home: README.md
    - Technical Setup:
      - Needs & Recommendations: setup/specs.md
      - Installation: setup/install.md
      - Device Setup: setup/tutorial.md
      - Program Recognition Tips: setup/camera-setup.md
    - Paper Documentation: 
      - Model-View-Controller Framework: use/mvc.md
      - Board Implementation: use/board-implementation.md
      - Board API: use/board-api.md
      - Legacy Paper API: use/paper-api.md
      - Example Paper Program: use/paper-tutorial.md
      - Downloads: resources.md
    - Community:
      - Contribute: CONTRIBUTING.md
      - Feature Wishlist: WISHLIST.md
      - Community Code of Conduct: CODE_OF_CONDUCT.md
      - Join Us: community.md