name: Sync Files
on:
  push:
    branches:
      - docs
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@main
      - name: Run GitHub File Sync
        uses: BetaHuhn/repo-file-sync-action@v1
        with:
          GH_PAT: ${{ secrets.BF_GH_PAT }}
          PR_LABELS: false
          # REVIEWERS: brettfiedler
          COMMIT_BODY: 'Repo File Sync auto update api doc main/dev branches'
          DRY_RUN: true
          SKIP_PR: true
